### ISSUE TITLE
能提供下初赛数据集供学习使用吗？

### ISSUE THREAD

**Issue by gdtydm** [zhpmatrix/tianchi-ruijin#3]
能提供下初赛数据集供学习使用吗？
我没参加比赛 拿不到数据集，希望你提供一下，非常感谢。961213106@qq.com

**Comment by zhpmatrix** [comment]
@Aifcce 之前实验室集群改造，导致我的备份数据出了问题。建议其他地方找一下吧，不好意思，应该可以找到的。
